name: build-and-deploy
on:
 # push:
 #   branches:
 #     - master
  watch:
    types: [started] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          # rm: 1 # 上传前先清空目录
          # source: 'dist' # 构建结果目录
          # target: 'nginx/html/blog' # 远程服务器 nginx 目录
          # strip_components: 1 # 如果不配置该参数，上传后的目录结构就是 nginx/html/blog/dist
          strip_components: 1
          source: "tests/a.txt,tests/b.txt"
          target: "ccx"

