name: build-and-deploy
on:
 # push:
 #   branches:
 #     - master
  watch:
    types: [started] 

env:
  UPLOAD_TO_N1: true
  AUTOSSH: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: 创建文件
        run: |
          mkdir -p openwrt/bin/targets/armvirt/64
          cp openwrt-armvirt-64-default-rootfs.tar.gz  "openwrt/bin/targets/armvirt/64/"
          cd openwrt/bin/targets/*/*
          mv openwrt-armvirt-64-default-rootfs.tar.gz  "Auto$(date +"%m%d")v$(($(date +"%H")+8))-op.tar.gz"

      - name: 上传固件到N1
        if: env.UPLOAD_TO_N1 == 'true'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          # rm: 1 # 上传前先清空目录
          # source: 'dist' # 构建结果目录
          # target: 'nginx/html/blog' # 远程服务器 nginx 目录
          # strip_components: 1 # 如果不配置该参数，上传后的目录结构就是 nginx/html/blog/dist
          source: "openwrt/bin/targets/armvirt/64/*.tar.gz"
          target: "ccx"
          strip_components: 5

      - name: ssh命令
        if: env.AUTOSSH == 'true' && failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd ccx && bash auto.sh



